export const PRODUCTS_REQUESTED = "PRODUCTS_REQUESTED";
export const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS";

export const CREATE_TAOBAO_PWD = "CREATE_TAOBAO_PWD";
export const CREATE_TAOBAO_PWD_SUCCESS = "CREATE_TAOBAO_PWD_SUCCESS";
